# Generated by Django 2.2.1 on 2019-05-16 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('flight_id', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('arrival_time', models.DateTimeField()),
                ('company', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('RG', 'Registration'), ('OW', 'On the way'), ('DL', 'Delayed'), ('CN', 'Canceled'), ('AR', 'Arrived'), ('DP', 'Departure')], default='RG', max_length=2)),
                ('is_departure', models.BooleanField(default=True)),
                ('is_arrival', models.BooleanField(default=False)),
                ('plane_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='crm.Plane')),
            ],
        ),
    ]
