# Generated by Django 2.2.1 on 2019-05-16 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='is_arrival',
        ),
    ]
