# Generated by Django 2.2.1 on 2019-05-17 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_remove_flight_is_arrival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='plane_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Plane'),
        ),
    ]
