# Generated by Django 2.2.1 on 2019-05-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20190519_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='slug',
            field=models.SlugField(blank=True, max_length=10, unique=True),
        ),
    ]
