# Generated by Django 2.2.1 on 2019-05-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20190517_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['-departure_time']},
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
