# Generated by Django 2.2.1 on 2019-05-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_flight_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='plane',
            name='seats',
            field=models.IntegerField(default=120),
        ),
    ]
